"""empty message

Revision ID: 622bac747faf
Revises: a41d0777b127
Create Date: 2021-02-23 00:31:58.479529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622bac747faf'
down_revision = 'a41d0777b127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('user', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_list', 'user')
    # ### end Alembic commands ###
