"""empty message

Revision ID: a41d0777b127
Revises: 01d5c239a26c
Create Date: 2021-02-23 00:06:27.522817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a41d0777b127'
down_revision = '01d5c239a26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('todo_list', sa.Column('label', sa.String(length=250), nullable=False))
    op.drop_column('todo_list', 'todo_list')
    op.drop_column('user', 'todo_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('todo_list', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('todo_list', sa.Column('todo_list', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('todo_list', 'label')
    op.drop_column('todo_list', 'done')
    # ### end Alembic commands ###
